services:
  api:
    image: golang:1.24.4-bookworm
    container_name: pdf_translator_api_dev
    volumes:
      - ./app:/app
    ports:
      - "${PORT:-3333}:3333"
    depends_on:
      - db
    env_file:
      - app/.env
    networks:
      - db
    command: ["tail", "-f", "/dev/null"]

  db:
    image: postgres:latest
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    environment:
      - TZ=${TIMEZONE}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_NAMESPACE=auth
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db
    restart: unless-stopped

networks:
  db:
