FROM golang:1.24.4-bookworm AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download && go mod verify

# Install Python and pdf2docx
RUN apt-get update && apt-get install -y python3 python3-pip python3-venv
RUN python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install pdf2docx

# Add the virtual environment to PATH
ENV PATH="/opt/venv/bin:$PATH"

CMD ["tail", "-f", "/dev/null"]